"""
Revision ID: 292708816bc0
Revises: 84662ac6b4eb
Create Date: 2025-07-17 00:45:54.510771

"""

revision = "292708816bc0"
down_revision = '84662ac6b4eb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('reasoning', sa.Text(), nullable=True))
    op.drop_column('leads', 'enriched_data')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('enriched_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('leads', 'reasoning')
    # ### end Alembic commands ###
