"""
Revision ID: 878d4a312ad6
Revises: add_lead_roi_probability
Create Date: 2025-07-16 21:12:26.018750

"""

revision = "878d4a312ad6"
down_revision = 'add_lead_roi_probability'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('insta_url', sa.String(length=256), nullable=True))
    op.add_column('businesses', sa.Column('insta_description', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('yelp_url', sa.String(length=256), nullable=True))
    op.add_column('businesses', sa.Column('yelp_description', sa.Text(), nullable=True))
    op.drop_column('businesses', 'social_media')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('social_media', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'yelp_description')
    op.drop_column('businesses', 'yelp_url')
    op.drop_column('businesses', 'insta_description')
    op.drop_column('businesses', 'insta_url')
    # ### end Alembic commands ###
