"""
Revision ID: b35775ce5ef9
Revises: bd377c44ac71
Create Date: 2025-07-16 23:17:45.805718

"""

revision = "b35775ce5ef9"
down_revision = 'bd377c44ac71'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('trends', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'trends')
    # ### end Alembic commands ###
